### ISSUE TITLE
Set an automatic module name in the Jar MANIFEST

### ISSUE THREAD

**Issue by carlosame** [rtyley/animated-gif-lib-for-java#13]
To use this project in JPMS modular builds, an automatic module name would be helpful; see the following blog post for context:

http://branchandbound.net/blog/java/2017/12/automatic-module-name/

The idea would be to add the following to the `pom.xml`, inside the build/plugins section:
```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-jar-plugin</artifactId>
  <version>3.2.0</version>
  <configuration>
    <archive>
      <manifestEntries>
        <Automatic-Module-Name>com.madgag.gif.fmsware</Automatic-Module-Name>
      </manifestEntries>
    </archive>
  </configuration>
</plugin>
```

**Comment by rtyley** [comment]
Hey thanks, this is interesting! Would you like to submit it as a PR?

**Comment by carlosame** [comment]
> Would you like to submit it as a PR?

Done.
