### ISSUE TITLE
Images imported as translucent lose quality when exported as a gif

### ISSUE THREAD

**Issue by TsundereBug** [rtyley/animated-gif-lib-for-java#5]
Original image:

![blob](https://user-images.githubusercontent.com/7751296/34085617-75f9fd28-e361-11e7-8669-307e8e6668a3.png)

When on a rotation and exported to gif:

![blob](https://user-images.githubusercontent.com/7751296/34085622-82b276da-e361-11e7-820c-fa00b2b9303a.gif)

When set to a background and transparency color of Black and perfect match as false:

![blob](https://user-images.githubusercontent.com/7751296/34085640-add4cfc0-e361-11e7-890c-47b54ff2546b.gif)

**Comment by TsundereBug** [comment]
This is a problem with how I read the images and merged them into a GIF.

**Comment by shaksternano** [comment]
May I asked what you did to fix this?

**Comment by s5bug** [comment]
I think what I did was prevent Alpha values from being not 1.0 or 0.0.

**Comment by shaksternano** [comment]
Thanks.
